package com.yishenghuang.keyic.ui.brand

import androidx.annotation.DrawableRes
import androidx.compose.ui.graphics.Color
import com.yishenghuang.keyic.R
import kotlin.math.abs

/**
 * Auto-generated from Streamline Logos solid (CC BY 4.0).
 * Source: https://streamlinehq.com — see app/NOTICE_STREAMLINE.txt
 * Do not edit by hand; re-run import script to refresh.
 */
object BrandCatalog {
    data class Entry(
        val id: String,
        val keys: List<String>,
        val color: Color,
        @param:DrawableRes val drawableRes: Int,
    )

    val entries: List<Entry> = listOf(
        Entry(
            id = "3ds-max",
            keys = listOf("3ds max", "3ds-max"),
            color = Color.hsl(337f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_n3ds_max,
        ),
        Entry(
            id = "500px",
            keys = listOf("500px"),
            color = Color.hsl(247f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_n500px,
        ),
        Entry(
            id = "about-me",
            keys = listOf("about me", "about-me"),
            color = Color.hsl(324f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_about_me,
        ),
        Entry(
            id = "adobe",
            keys = listOf("adobe"),
            color = Color(0xFFFF0000),
            drawableRes = R.drawable.ic_brand_adobe,
        ),
        Entry(
            id = "adobe-after-effects",
            keys = listOf("adobe after effects", "adobe-after-effects"),
            color = Color.hsl(331f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_adobe_after_effects,
        ),
        Entry(
            id = "adobe-animate",
            keys = listOf("adobe animate", "adobe-animate"),
            color = Color.hsl(103f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_adobe_animate,
        ),
        Entry(
            id = "adobe-audio",
            keys = listOf("adobe audio", "adobe-audio"),
            color = Color.hsl(2f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_adobe_audio,
        ),
        Entry(
            id = "adobe-bridge",
            keys = listOf("adobe bridge", "adobe-bridge"),
            color = Color.hsl(117f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_adobe_bridge,
        ),
        Entry(
            id = "adobe-cloud",
            keys = listOf("adobe cloud", "adobe-cloud"),
            color = Color.hsl(153f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_adobe_cloud,
        ),
        Entry(
            id = "adobe-illustrator",
            keys = listOf("adobe illustrator", "adobe-illustrator"),
            color = Color.hsl(61f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_adobe_illustrator,
        ),
        Entry(
            id = "adobe-indesign",
            keys = listOf("adobe indesign", "adobe-indesign"),
            color = Color.hsl(31f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_adobe_indesign,
        ),
        Entry(
            id = "adobe-lightroom",
            keys = listOf("adobe lightroom", "adobe-lightroom"),
            color = Color.hsl(107f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_adobe_lightroom,
        ),
        Entry(
            id = "adobe-photoshop",
            keys = listOf("adobe photoshop", "adobe-photoshop"),
            color = Color.hsl(316f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_adobe_photoshop,
        ),
        Entry(
            id = "adobe-premiere-pro",
            keys = listOf("adobe premiere pro", "adobe-premiere-pro"),
            color = Color.hsl(301f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_adobe_premiere_pro,
        ),
        Entry(
            id = "adobe-xd",
            keys = listOf("adobe xd", "adobe-xd"),
            color = Color.hsl(80f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_adobe_xd,
        ),
        Entry(
            id = "affinity",
            keys = listOf("affinity"),
            color = Color.hsl(266f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_affinity,
        ),
        Entry(
            id = "affinity-designer",
            keys = listOf("affinity designer", "affinity-designer"),
            color = Color.hsl(112f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_affinity_designer,
        ),
        Entry(
            id = "affinity-photo",
            keys = listOf("affinity photo", "affinity-photo"),
            color = Color.hsl(27f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_affinity_photo,
        ),
        Entry(
            id = "affinity-publiser",
            keys = listOf("affinity publiser", "affinity-publiser"),
            color = Color.hsl(113f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_affinity_publiser,
        ),
        Entry(
            id = "aim",
            keys = listOf("aim"),
            color = Color.hsl(349f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_aim,
        ),
        Entry(
            id = "alipay",
            keys = listOf("alipay"),
            color = Color(0xFF1677FF),
            drawableRes = R.drawable.ic_brand_alipay,
        ),
        Entry(
            id = "alpine-linux",
            keys = listOf("alpine linux", "alpine-linux"),
            color = Color.hsl(242f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_alpine_linux,
        ),
        Entry(
            id = "amazon",
            keys = listOf("amazon"),
            color = Color(0xFFFF9900),
            drawableRes = R.drawable.ic_brand_amazon,
        ),
        Entry(
            id = "amazon-luna",
            keys = listOf("amazon luna", "amazon-luna"),
            color = Color.hsl(353f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_amazon_luna,
        ),
        Entry(
            id = "amazon-prime-video",
            keys = listOf("amazon prime video", "amazon-prime-video", "prime video", "primevideo"),
            color = Color.hsl(286f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_amazon_prime_video,
        ),
        Entry(
            id = "amazon-web-service",
            keys = listOf("amazon web service", "amazon-web-service", "aws", "amazon aws"),
            color = Color.hsl(253f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_amazon_web_service,
        ),
        Entry(
            id = "amd",
            keys = listOf("amd"),
            color = Color.hsl(8f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_amd,
        ),
        Entry(
            id = "american-express",
            keys = listOf("american express", "american-express", "amex"),
            color = Color.hsl(321f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_american_express,
        ),
        Entry(
            id = "analogue",
            keys = listOf("analogue"),
            color = Color.hsl(288f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_analogue,
        ),
        Entry(
            id = "anchor",
            keys = listOf("anchor"),
            color = Color.hsl(93f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_anchor,
        ),
        Entry(
            id = "android",
            keys = listOf("android"),
            color = Color.hsl(259f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_android,
        ),
        Entry(
            id = "androidauto",
            keys = listOf("androidauto"),
            color = Color.hsl(250f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_androidauto,
        ),
        Entry(
            id = "angular",
            keys = listOf("angular"),
            color = Color.hsl(56f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_angular,
        ),
        Entry(
            id = "apache-netbeans",
            keys = listOf("apache netbeans", "apache-netbeans"),
            color = Color.hsl(191f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_apache_netbeans,
        ),
        Entry(
            id = "apple",
            keys = listOf("apple", "icloud"),
            color = Color(0xFF555555),
            drawableRes = R.drawable.ic_brand_apple,
        ),
        Entry(
            id = "apple-ios",
            keys = listOf("apple ios", "apple-ios"),
            color = Color.hsl(54f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_apple_ios,
        ),
        Entry(
            id = "apple-podcast",
            keys = listOf("apple podcast", "apple-podcast"),
            color = Color.hsl(279f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_apple_podcast,
        ),
        Entry(
            id = "app-store",
            keys = listOf("app store", "app-store", "appstore"),
            color = Color.hsl(173f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_app_store,
        ),
        Entry(
            id = "arch-linux",
            keys = listOf("arch linux", "arch-linux"),
            color = Color.hsl(319f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_arch_linux,
        ),
        Entry(
            id = "askfm",
            keys = listOf("askfm"),
            color = Color.hsl(358f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_askfm,
        ),
        Entry(
            id = "ati",
            keys = listOf("ati"),
            color = Color.hsl(214f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_ati,
        ),
        Entry(
            id = "atlassian",
            keys = listOf("atlassian"),
            color = Color.hsl(354f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_atlassian,
        ),
        Entry(
            id = "audacity",
            keys = listOf("audacity"),
            color = Color.hsl(132f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_audacity,
        ),
        Entry(
            id = "authy",
            keys = listOf("authy"),
            color = Color.hsl(311f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_authy,
        ),
        Entry(
            id = "autodesk",
            keys = listOf("autodesk"),
            color = Color.hsl(44f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_autodesk,
        ),
        Entry(
            id = "backbonejs",
            keys = listOf("backbonejs"),
            color = Color.hsl(320f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_backbonejs,
        ),
        Entry(
            id = "badoo",
            keys = listOf("badoo"),
            color = Color.hsl(179f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_badoo,
        ),
        Entry(
            id = "bandcamp",
            keys = listOf("bandcamp"),
            color = Color.hsl(164f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_bandcamp,
        ),
        Entry(
            id = "basecamp",
            keys = listOf("basecamp"),
            color = Color.hsl(286f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_basecamp,
        ),
        Entry(
            id = "bbc-iplayer",
            keys = listOf("bbc iplayer", "bbc-iplayer"),
            color = Color.hsl(16f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_bbc_iplayer,
        ),
        Entry(
            id = "beats-studio",
            keys = listOf("beats studio", "beats-studio"),
            color = Color.hsl(272f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_beats_studio,
        ),
        Entry(
            id = "bebo",
            keys = listOf("bebo"),
            color = Color.hsl(232f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_bebo,
        ),
        Entry(
            id = "behance",
            keys = listOf("behance"),
            color = Color.hsl(98f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_behance,
        ),
        Entry(
            id = "betalist",
            keys = listOf("betalist"),
            color = Color.hsl(72f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_betalist,
        ),
        Entry(
            id = "beyondcorp-enterprise",
            keys = listOf("beyondcorp enterprise", "beyondcorp-enterprise"),
            color = Color.hsl(97f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_beyondcorp_enterprise,
        ),
        Entry(
            id = "bilibili",
            keys = listOf("bilibili"),
            color = Color(0xFFFB7299),
            drawableRes = R.drawable.ic_brand_bilibili,
        ),
        Entry(
            id = "bing",
            keys = listOf("bing"),
            color = Color.hsl(32f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_bing,
        ),
        Entry(
            id = "bitbucket",
            keys = listOf("bitbucket", "bit bucket"),
            color = Color.hsl(129f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_bitbucket,
        ),
        Entry(
            id = "blackberry",
            keys = listOf("blackberry"),
            color = Color.hsl(297f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_blackberry,
        ),
        Entry(
            id = "blogger",
            keys = listOf("blogger"),
            color = Color.hsl(20f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_blogger,
        ),
        Entry(
            id = "bloglovin",
            keys = listOf("bloglovin"),
            color = Color.hsl(356f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_bloglovin,
        ),
        Entry(
            id = "bnter",
            keys = listOf("bnter"),
            color = Color.hsl(295f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_bnter,
        ),
        Entry(
            id = "bootstrap",
            keys = listOf("bootstrap"),
            color = Color.hsl(336f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_bootstrap,
        ),
        Entry(
            id = "bower",
            keys = listOf("bower"),
            color = Color.hsl(157f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_bower,
        ),
        Entry(
            id = "box",
            keys = listOf("box"),
            color = Color.hsl(305f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_box,
        ),
        Entry(
            id = "brightkite",
            keys = listOf("brightkite"),
            color = Color.hsl(351f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_brightkite,
        ),
        Entry(
            id = "broadcom",
            keys = listOf("broadcom"),
            color = Color.hsl(187f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_broadcom,
        ),
        Entry(
            id = "bugsnag",
            keys = listOf("bugsnag"),
            color = Color.hsl(157f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_bugsnag,
        ),
        Entry(
            id = "byte",
            keys = listOf("byte"),
            color = Color.hsl(88f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_byte,
        ),
        Entry(
            id = "campaign-monitor",
            keys = listOf("campaign monitor", "campaign-monitor"),
            color = Color.hsl(327f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_campaign_monitor,
        ),
        Entry(
            id = "canonical",
            keys = listOf("canonical"),
            color = Color.hsl(176f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_canonical,
        ),
        Entry(
            id = "centos",
            keys = listOf("centos"),
            color = Color.hsl(330f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_centos,
        ),
        Entry(
            id = "cinema-4d",
            keys = listOf("cinema 4d", "cinema-4d"),
            color = Color.hsl(288f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_cinema_4d,
        ),
        Entry(
            id = "c-language",
            keys = listOf("c language", "c-language"),
            color = Color.hsl(280f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_c_language,
        ),
        Entry(
            id = "claris",
            keys = listOf("claris"),
            color = Color.hsl(18f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_claris,
        ),
        Entry(
            id = "cloudsmith",
            keys = listOf("cloudsmith"),
            color = Color.hsl(326f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_cloudsmith,
        ),
        Entry(
            id = "cnn",
            keys = listOf("cnn"),
            color = Color.hsl(241f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_cnn,
        ),
        Entry(
            id = "code-climate",
            keys = listOf("code climate", "code-climate"),
            color = Color.hsl(57f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_code_climate,
        ),
        Entry(
            id = "codecov",
            keys = listOf("codecov"),
            color = Color.hsl(103f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_codecov,
        ),
        Entry(
            id = "codefactor",
            keys = listOf("codefactor"),
            color = Color.hsl(240f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_codefactor,
        ),
        Entry(
            id = "codeigniter",
            keys = listOf("codeigniter"),
            color = Color.hsl(359f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_codeigniter,
        ),
        Entry(
            id = "codepen",
            keys = listOf("codepen"),
            color = Color.hsl(290f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_codepen,
        ),
        Entry(
            id = "code-sandbox",
            keys = listOf("code sandbox", "code-sandbox"),
            color = Color.hsl(227f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_code_sandbox,
        ),
        Entry(
            id = "consul",
            keys = listOf("consul"),
            color = Color.hsl(34f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_consul,
        ),
        Entry(
            id = "coroflot",
            keys = listOf("coroflot"),
            color = Color.hsl(38f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_coroflot,
        ),
        Entry(
            id = "c-plus-language",
            keys = listOf("c plus language", "c-plus-language"),
            color = Color.hsl(73f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_c_plus_language,
        ),
        Entry(
            id = "creative-commons",
            keys = listOf("creative commons", "creative-commons"),
            color = Color.hsl(72f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_creative_commons,
        ),
        Entry(
            id = "crowdin",
            keys = listOf("crowdin"),
            color = Color.hsl(96f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_crowdin,
        ),
        Entry(
            id = "crunchyroll",
            keys = listOf("crunchyroll"),
            color = Color.hsl(141f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_crunchyroll,
        ),
        Entry(
            id = "cryengine",
            keys = listOf("cryengine"),
            color = Color.hsl(252f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_cryengine,
        ),
        Entry(
            id = "cucumber-io",
            keys = listOf("cucumber io", "cucumber-io"),
            color = Color.hsl(347f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_cucumber_io,
        ),
        Entry(
            id = "d3js",
            keys = listOf("d3js"),
            color = Color.hsl(52f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_d3js,
        ),
        Entry(
            id = "dailybooth",
            keys = listOf("dailybooth"),
            color = Color.hsl(83f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_dailybooth,
        ),
        Entry(
            id = "dailymotion",
            keys = listOf("dailymotion"),
            color = Color.hsl(321f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_dailymotion,
        ),
        Entry(
            id = "dart",
            keys = listOf("dart"),
            color = Color.hsl(339f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_dart,
        ),
        Entry(
            id = "daytum",
            keys = listOf("daytum"),
            color = Color.hsl(250f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_daytum,
        ),
        Entry(
            id = "deezer",
            keys = listOf("deezer"),
            color = Color.hsl(87f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_deezer,
        ),
        Entry(
            id = "deliciousing",
            keys = listOf("deliciousing"),
            color = Color.hsl(341f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_deliciousing,
        ),
        Entry(
            id = "design-bump",
            keys = listOf("design bump", "design-bump"),
            color = Color.hsl(277f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_design_bump,
        ),
        Entry(
            id = "design-float",
            keys = listOf("design float", "design-float"),
            color = Color.hsl(207f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_design_float,
        ),
        Entry(
            id = "designmoo",
            keys = listOf("designmoo"),
            color = Color.hsl(33f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_designmoo,
        ),
        Entry(
            id = "deviant-art",
            keys = listOf("deviant art", "deviant-art"),
            color = Color.hsl(223f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_deviant_art,
        ),
        Entry(
            id = "devicon",
            keys = listOf("devicon"),
            color = Color.hsl(272f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_devicon,
        ),
        Entry(
            id = "digg",
            keys = listOf("digg"),
            color = Color.hsl(355f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_digg,
        ),
        Entry(
            id = "digital-ocean",
            keys = listOf("digital ocean", "digital-ocean"),
            color = Color.hsl(145f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_digital_ocean,
        ),
        Entry(
            id = "diigo",
            keys = listOf("diigo"),
            color = Color.hsl(250f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_diigo,
        ),
        Entry(
            id = "discord",
            keys = listOf("discord"),
            color = Color(0xFF5865F2),
            drawableRes = R.drawable.ic_brand_discord,
        ),
        Entry(
            id = "discourse",
            keys = listOf("discourse"),
            color = Color.hsl(81f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_discourse,
        ),
        Entry(
            id = "disney-plus",
            keys = listOf("disney plus", "disney-plus"),
            color = Color.hsl(53f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_disney_plus,
        ),
        Entry(
            id = "docker",
            keys = listOf("docker"),
            color = Color.hsl(154f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_docker,
        ),
        Entry(
            id = "doctrine",
            keys = listOf("doctrine"),
            color = Color.hsl(352f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_doctrine,
        ),
        Entry(
            id = "douban",
            keys = listOf("douban"),
            color = Color.hsl(69f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_douban,
        ),
        Entry(
            id = "dribbble",
            keys = listOf("dribbble"),
            color = Color.hsl(312f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_dribbble,
        ),
        Entry(
            id = "dropbox",
            keys = listOf("dropbox"),
            color = Color(0xFF0061FF),
            drawableRes = R.drawable.ic_brand_dropbox,
        ),
        Entry(
            id = "drupal",
            keys = listOf("drupal"),
            color = Color.hsl(116f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_drupal,
        ),
        Entry(
            id = "eclipse-ide",
            keys = listOf("eclipse ide", "eclipse-ide"),
            color = Color.hsl(126f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_eclipse_ide,
        ),
        Entry(
            id = "egnyte",
            keys = listOf("egnyte"),
            color = Color.hsl(168f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_egnyte,
        ),
        Entry(
            id = "elastic",
            keys = listOf("elastic"),
            color = Color.hsl(77f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_elastic,
        ),
        Entry(
            id = "elastic-beats",
            keys = listOf("elastic beats", "elastic-beats"),
            color = Color.hsl(201f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_elastic_beats,
        ),
        Entry(
            id = "elastic-cloud",
            keys = listOf("elastic cloud", "elastic-cloud"),
            color = Color.hsl(159f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_elastic_cloud,
        ),
        Entry(
            id = "elastic-logstash",
            keys = listOf("elastic logstash", "elastic-logstash"),
            color = Color.hsl(255f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_elastic_logstash,
        ),
        Entry(
            id = "elastic-search",
            keys = listOf("elastic search", "elastic-search"),
            color = Color.hsl(284f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_elastic_search,
        ),
        Entry(
            id = "elastic-stack",
            keys = listOf("elastic stack", "elastic-stack"),
            color = Color.hsl(132f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_elastic_stack,
        ),
        Entry(
            id = "elastic-x-pack",
            keys = listOf("elastic x pack", "elastic-x-pack"),
            color = Color.hsl(94f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_elastic_x_pack,
        ),
        Entry(
            id = "electronic-arts",
            keys = listOf("electronic arts", "electronic-arts"),
            color = Color.hsl(101f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_electronic_arts,
        ),
        Entry(
            id = "elixir",
            keys = listOf("elixir"),
            color = Color.hsl(207f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_elixir,
        ),
        Entry(
            id = "ello",
            keys = listOf("ello"),
            color = Color.hsl(194f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_ello,
        ),
        Entry(
            id = "email",
            keys = listOf("email"),
            color = Color.hsl(58f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_email,
        ),
        Entry(
            id = "epic-games",
            keys = listOf("epic games", "epic-games"),
            color = Color.hsl(229f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_epic_games,
        ),
        Entry(
            id = "esea",
            keys = listOf("esea"),
            color = Color.hsl(104f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_esea,
        ),
        Entry(
            id = "eslint",
            keys = listOf("eslint"),
            color = Color.hsl(1f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_eslint,
        ),
        Entry(
            id = "etsy",
            keys = listOf("etsy"),
            color = Color.hsl(155f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_etsy,
        ),
        Entry(
            id = "evernote",
            keys = listOf("evernote"),
            color = Color.hsl(226f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_evernote,
        ),
        Entry(
            id = "eyeem",
            keys = listOf("eyeem"),
            color = Color.hsl(333f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_eyeem,
        ),
        Entry(
            id = "facebook",
            keys = listOf("facebook", "fb.com", "meta"),
            color = Color(0xFF1877F2),
            drawableRes = R.drawable.ic_brand_facebook,
        ),
        Entry(
            id = "facebook-gaming",
            keys = listOf("facebook gaming", "facebook-gaming"),
            color = Color.hsl(52f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_facebook_gaming,
        ),
        Entry(
            id = "facebook-messenger",
            keys = listOf("facebook messenger", "facebook-messenger"),
            color = Color.hsl(292f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_facebook_messenger,
        ),
        Entry(
            id = "fandom",
            keys = listOf("fandom"),
            color = Color.hsl(51f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_fandom,
        ),
        Entry(
            id = "f-droid",
            keys = listOf("f droid", "f-droid"),
            color = Color.hsl(227f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_f_droid,
        ),
        Entry(
            id = "feathub",
            keys = listOf("feathub"),
            color = Color.hsl(221f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_feathub,
        ),
        Entry(
            id = "fedora",
            keys = listOf("fedora"),
            color = Color.hsl(277f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_fedora,
        ),
        Entry(
            id = "feed-burner",
            keys = listOf("feed burner", "feed-burner"),
            color = Color.hsl(159f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_feed_burner,
        ),
        Entry(
            id = "feedly",
            keys = listOf("feedly"),
            color = Color.hsl(301f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_feedly,
        ),
        Entry(
            id = "ffffounding",
            keys = listOf("ffffounding"),
            color = Color.hsl(140f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_ffffounding,
        ),
        Entry(
            id = "figma",
            keys = listOf("figma"),
            color = Color.hsl(238f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_figma,
        ),
        Entry(
            id = "firebase",
            keys = listOf("firebase"),
            color = Color.hsl(65f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_firebase,
        ),
        Entry(
            id = "fitbit",
            keys = listOf("fitbit"),
            color = Color.hsl(136f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_fitbit,
        ),
        Entry(
            id = "flickr",
            keys = listOf("flickr"),
            color = Color.hsl(207f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_flickr,
        ),
        Entry(
            id = "flipboard",
            keys = listOf("flipboard"),
            color = Color.hsl(313f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_flipboard,
        ),
        Entry(
            id = "flutter",
            keys = listOf("flutter"),
            color = Color.hsl(112f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_flutter,
        ),
        Entry(
            id = "food-spotting",
            keys = listOf("food spotting", "food-spotting"),
            color = Color.hsl(293f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_food_spotting,
        ),
        Entry(
            id = "formspirng",
            keys = listOf("formspirng"),
            color = Color.hsl(311f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_formspirng,
        ),
        Entry(
            id = "forrst",
            keys = listOf("forrst"),
            color = Color.hsl(26f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_forrst,
        ),
        Entry(
            id = "foursquare",
            keys = listOf("foursquare"),
            color = Color.hsl(347f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_foursquare,
        ),
        Entry(
            id = "framer",
            keys = listOf("framer"),
            color = Color.hsl(47f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_framer,
        ),
        Entry(
            id = "friends-feed",
            keys = listOf("friends feed", "friends-feed"),
            color = Color.hsl(42f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_friends_feed,
        ),
        Entry(
            id = "funimation",
            keys = listOf("funimation"),
            color = Color.hsl(22f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_funimation,
        ),
        Entry(
            id = "gabbr",
            keys = listOf("gabbr"),
            color = Color.hsl(240f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_gabbr,
        ),
        Entry(
            id = "gamercastering",
            keys = listOf("gamercastering"),
            color = Color.hsl(314f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_gamercastering,
        ),
        Entry(
            id = "gdgt",
            keys = listOf("gdgt"),
            color = Color.hsl(286f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_gdgt,
        ),
        Entry(
            id = "geforce-now",
            keys = listOf("geforce now", "geforce-now"),
            color = Color.hsl(104f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_geforce_now,
        ),
        Entry(
            id = "github",
            keys = listOf("github", "gh.com"),
            color = Color(0xFF24292F),
            drawableRes = R.drawable.ic_brand_github,
        ),
        Entry(
            id = "gog-com",
            keys = listOf("gog com", "gog-com"),
            color = Color.hsl(59f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_gog_com,
        ),
        Entry(
            id = "google",
            keys = listOf("google", "gstatic"),
            color = Color(0xFFEA4335),
            drawableRes = R.drawable.ic_brand_google,
        ),
        Entry(
            id = "google-ads",
            keys = listOf("google ads", "google-ads"),
            color = Color.hsl(202f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_ads,
        ),
        Entry(
            id = "google-adsense",
            keys = listOf("google adsense", "google-adsense"),
            color = Color.hsl(291f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_adsense,
        ),
        Entry(
            id = "google-assistant",
            keys = listOf("google assistant", "google-assistant"),
            color = Color.hsl(120f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_assistant,
        ),
        Entry(
            id = "google-buzz",
            keys = listOf("google buzz", "google-buzz"),
            color = Color.hsl(227f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_buzz,
        ),
        Entry(
            id = "google-calendar",
            keys = listOf("google calendar", "google-calendar"),
            color = Color.hsl(114f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_calendar,
        ),
        Entry(
            id = "google-cast",
            keys = listOf("google cast", "google-cast"),
            color = Color.hsl(345f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_cast,
        ),
        Entry(
            id = "google-chat",
            keys = listOf("google chat", "google-chat"),
            color = Color.hsl(178f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_chat,
        ),
        Entry(
            id = "google-cloud",
            keys = listOf("google cloud", "google-cloud"),
            color = Color.hsl(355f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_cloud,
        ),
        Entry(
            id = "google-drive",
            keys = listOf("google drive", "google-drive", "drive.google"),
            color = Color.hsl(8f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_drive,
        ),
        Entry(
            id = "google-fit",
            keys = listOf("google fit", "google-fit"),
            color = Color.hsl(335f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_fit,
        ),
        Entry(
            id = "google-hangouts",
            keys = listOf("google hangouts", "google-hangouts"),
            color = Color.hsl(51f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_hangouts,
        ),
        Entry(
            id = "google-hangouts-chat",
            keys = listOf("google hangouts chat", "google-hangouts-chat"),
            color = Color.hsl(26f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_hangouts_chat,
        ),
        Entry(
            id = "google-hangouts-meet",
            keys = listOf("google hangouts meet", "google-hangouts-meet"),
            color = Color.hsl(95f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_hangouts_meet,
        ),
        Entry(
            id = "google-home",
            keys = listOf("google home", "google-home"),
            color = Color.hsl(175f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_home,
        ),
        Entry(
            id = "google-lens",
            keys = listOf("google lens", "google-lens"),
            color = Color.hsl(292f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_lens,
        ),
        Entry(
            id = "google-mail",
            keys = listOf("google mail", "google-mail", "gmail"),
            color = Color.hsl(283f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_mail,
        ),
        Entry(
            id = "google-maps",
            keys = listOf("google maps", "google-maps"),
            color = Color.hsl(113f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_maps,
        ),
        Entry(
            id = "google-meet",
            keys = listOf("google meet", "google-meet"),
            color = Color.hsl(165f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_meet,
        ),
        Entry(
            id = "google-microphone-voice-search",
            keys = listOf("google microphone voice search", "google-microphone-voice-search"),
            color = Color.hsl(246f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_microphone_voice_search,
        ),
        Entry(
            id = "google-near-by",
            keys = listOf("google near by", "google-near-by"),
            color = Color.hsl(256f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_near_by,
        ),
        Entry(
            id = "google-news",
            keys = listOf("google news", "google-news"),
            color = Color.hsl(193f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_news,
        ),
        Entry(
            id = "google-photos",
            keys = listOf("google photos", "google-photos"),
            color = Color.hsl(61f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_photos,
        ),
        Entry(
            id = "google-play",
            keys = listOf("google play", "google-play", "play.google"),
            color = Color.hsl(110f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_play,
        ),
        Entry(
            id = "google-plus",
            keys = listOf("google plus", "google-plus"),
            color = Color.hsl(36f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_plus,
        ),
        Entry(
            id = "google-podcast",
            keys = listOf("google podcast", "google-podcast"),
            color = Color.hsl(352f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_podcast,
        ),
        Entry(
            id = "google-shopping",
            keys = listOf("google shopping", "google-shopping"),
            color = Color.hsl(148f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_shopping,
        ),
        Entry(
            id = "google-stadia",
            keys = listOf("google stadia", "google-stadia"),
            color = Color.hsl(316f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_stadia,
        ),
        Entry(
            id = "google-surveys",
            keys = listOf("google surveys", "google-surveys"),
            color = Color.hsl(145f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_surveys,
        ),
        Entry(
            id = "google-tab-manager",
            keys = listOf("google tab manager", "google-tab-manager"),
            color = Color.hsl(109f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_tab_manager,
        ),
        Entry(
            id = "google-talk",
            keys = listOf("google talk", "google-talk"),
            color = Color.hsl(322f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_google_talk,
        ),
        Entry(
            id = "gowalla",
            keys = listOf("gowalla"),
            color = Color.hsl(51f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_gowalla,
        ),
        Entry(
            id = "grooveshark",
            keys = listOf("grooveshark"),
            color = Color.hsl(245f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_grooveshark,
        ),
        Entry(
            id = "guildeding",
            keys = listOf("guildeding"),
            color = Color.hsl(280f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_guildeding,
        ),
        Entry(
            id = "hbo-max",
            keys = listOf("hbo max", "hbo-max"),
            color = Color.hsl(278f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_hbo_max,
        ),
        Entry(
            id = "hi-five",
            keys = listOf("hi five", "hi-five"),
            color = Color.hsl(80f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_hi_five,
        ),
        Entry(
            id = "hulu-live-tv",
            keys = listOf("hulu live tv", "hulu-live-tv"),
            color = Color.hsl(280f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_hulu_live_tv,
        ),
        Entry(
            id = "hyves",
            keys = listOf("hyves"),
            color = Color.hsl(349f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_hyves,
        ),
        Entry(
            id = "iconjar",
            keys = listOf("iconjar"),
            color = Color.hsl(208f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_iconjar,
        ),
        Entry(
            id = "iconmoon",
            keys = listOf("iconmoon"),
            color = Color.hsl(178f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_iconmoon,
        ),
        Entry(
            id = "icq",
            keys = listOf("icq"),
            color = Color.hsl(309f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_icq,
        ),
        Entry(
            id = "identica",
            keys = listOf("identica"),
            color = Color.hsl(1f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_identica,
        ),
        Entry(
            id = "imdb",
            keys = listOf("imdb"),
            color = Color.hsl(162f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_imdb,
        ),
        Entry(
            id = "imessage",
            keys = listOf("imessage"),
            color = Color.hsl(224f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_imessage,
        ),
        Entry(
            id = "imgur",
            keys = listOf("imgur"),
            color = Color.hsl(98f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_imgur,
        ),
        Entry(
            id = "inkscape",
            keys = listOf("inkscape"),
            color = Color.hsl(352f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_inkscape,
        ),
        Entry(
            id = "instagram",
            keys = listOf("instagram"),
            color = Color(0xFFE4405F),
            drawableRes = R.drawable.ic_brand_instagram,
        ),
        Entry(
            id = "instapaper",
            keys = listOf("instapaper"),
            color = Color.hsl(213f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_instapaper,
        ),
        Entry(
            id = "invision",
            keys = listOf("invision"),
            color = Color.hsl(103f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_invision,
        ),
        Entry(
            id = "iq",
            keys = listOf("iq"),
            color = Color.hsl(264f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_iq,
        ),
        Entry(
            id = "irc-galleria",
            keys = listOf("irc galleria", "irc-galleria"),
            color = Color.hsl(196f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_irc_galleria,
        ),
        Entry(
            id = "itunes",
            keys = listOf("itunes"),
            color = Color.hsl(280f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_itunes,
        ),
        Entry(
            id = "iwiw",
            keys = listOf("iwiw"),
            color = Color.hsl(110f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_iwiw,
        ),
        Entry(
            id = "jira-software",
            keys = listOf("jira software", "jira-software"),
            color = Color.hsl(72f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_jira_software,
        ),
        Entry(
            id = "jpeg",
            keys = listOf("jpeg"),
            color = Color.hsl(348f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_jpeg,
        ),
        Entry(
            id = "kai-os",
            keys = listOf("kai os", "kai-os"),
            color = Color.hsl(186f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_kai_os,
        ),
        Entry(
            id = "kakao-talk",
            keys = listOf("kakao talk", "kakao-talk"),
            color = Color.hsl(140f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_kakao_talk,
        ),
        Entry(
            id = "kibana",
            keys = listOf("kibana"),
            color = Color.hsl(298f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_kibana,
        ),
        Entry(
            id = "kick-logo",
            keys = listOf("kick logo", "kick-logo"),
            color = Color.hsl(164f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_kick_logo,
        ),
        Entry(
            id = "kik",
            keys = listOf("kik"),
            color = Color.hsl(73f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_kik,
        ),
        Entry(
            id = "kodi",
            keys = listOf("kodi"),
            color = Color.hsl(7f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_kodi,
        ),
        Entry(
            id = "kotlin",
            keys = listOf("kotlin"),
            color = Color.hsl(357f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_kotlin,
        ),
        Entry(
            id = "laravel",
            keys = listOf("laravel"),
            color = Color.hsl(263f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_laravel,
        ),
        Entry(
            id = "lastfm",
            keys = listOf("lastfm"),
            color = Color.hsl(131f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_lastfm,
        ),
        Entry(
            id = "lastpass",
            keys = listOf("lastpass", "last pass"),
            color = Color.hsl(267f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_lastpass,
        ),
        Entry(
            id = "lineage",
            keys = listOf("lineage"),
            color = Color.hsl(49f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_lineage,
        ),
        Entry(
            id = "line-app",
            keys = listOf("line app", "line-app"),
            color = Color.hsl(50f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_line_app,
        ),
        Entry(
            id = "linkedin",
            keys = listOf("linkedin", "linked in"),
            color = Color(0xFF0A66C2),
            drawableRes = R.drawable.ic_brand_linkedin,
        ),
        Entry(
            id = "linux-mint",
            keys = listOf("linux mint", "linux-mint"),
            color = Color.hsl(49f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_linux_mint,
        ),
        Entry(
            id = "livejournal",
            keys = listOf("livejournal"),
            color = Color.hsl(205f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_livejournal,
        ),
        Entry(
            id = "logmein",
            keys = listOf("logmein"),
            color = Color.hsl(301f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_logmein,
        ),
        Entry(
            id = "loom",
            keys = listOf("loom"),
            color = Color.hsl(345f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_loom,
        ),
        Entry(
            id = "lubuntu",
            keys = listOf("lubuntu"),
            color = Color.hsl(203f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_lubuntu,
        ),
        Entry(
            id = "lyft",
            keys = listOf("lyft"),
            color = Color.hsl(159f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_lyft,
        ),
        Entry(
            id = "mac-finder",
            keys = listOf("mac finder", "mac-finder"),
            color = Color.hsl(284f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_mac_finder,
        ),
        Entry(
            id = "macos-osx",
            keys = listOf("macos osx", "macos-osx"),
            color = Color.hsl(272f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_macos_osx,
        ),
        Entry(
            id = "magento",
            keys = listOf("magento"),
            color = Color.hsl(281f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_magento,
        ),
        Entry(
            id = "manjaro",
            keys = listOf("manjaro"),
            color = Color.hsl(44f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_manjaro,
        ),
        Entry(
            id = "mastercard",
            keys = listOf("mastercard"),
            color = Color.hsl(34f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_mastercard,
        ),
        Entry(
            id = "mastodon",
            keys = listOf("mastodon"),
            color = Color.hsl(229f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_mastodon,
        ),
        Entry(
            id = "maya",
            keys = listOf("maya"),
            color = Color.hsl(258f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_maya,
        ),
        Entry(
            id = "mcafee",
            keys = listOf("mcafee"),
            color = Color.hsl(171f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_mcafee,
        ),
        Entry(
            id = "medium",
            keys = listOf("medium"),
            color = Color.hsl(221f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_medium,
        ),
        Entry(
            id = "meetup",
            keys = listOf("meetup"),
            color = Color.hsl(332f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_meetup,
        ),
        Entry(
            id = "memori",
            keys = listOf("memori"),
            color = Color.hsl(195f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_memori,
        ),
        Entry(
            id = "messages",
            keys = listOf("messages"),
            color = Color.hsl(10f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_messages,
        ),
        Entry(
            id = "meta-cafe",
            keys = listOf("meta cafe", "meta-cafe"),
            color = Color.hsl(135f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_meta_cafe,
        ),
        Entry(
            id = "microsoft",
            keys = listOf("microsoft", "outlook", "hotmail", "live.com", "office365", "office 365"),
            color = Color(0xFF00A4EF),
            drawableRes = R.drawable.ic_brand_microsoft,
        ),
        Entry(
            id = "microsoft-azure",
            keys = listOf("microsoft azure", "microsoft-azure"),
            color = Color.hsl(316f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_microsoft_azure,
        ),
        Entry(
            id = "microsoft-dynamics",
            keys = listOf("microsoft dynamics", "microsoft-dynamics"),
            color = Color.hsl(15f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_microsoft_dynamics,
        ),
        Entry(
            id = "microsoft-onedrive",
            keys = listOf("microsoft onedrive", "microsoft-onedrive", "onedrive", "one drive"),
            color = Color.hsl(183f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_microsoft_onedrive,
        ),
        Entry(
            id = "microsoft-sharepoint",
            keys = listOf("microsoft sharepoint", "microsoft-sharepoint"),
            color = Color.hsl(346f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_microsoft_sharepoint,
        ),
        Entry(
            id = "microsoft-teams",
            keys = listOf("microsoft teams", "microsoft-teams", "ms teams", "teams.microsoft"),
            color = Color.hsl(9f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_microsoft_teams,
        ),
        Entry(
            id = "microsoft-windows",
            keys = listOf("microsoft windows", "microsoft-windows"),
            color = Color.hsl(246f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_microsoft_windows,
        ),
        Entry(
            id = "microsoft-yammer",
            keys = listOf("microsoft yammer", "microsoft-yammer"),
            color = Color.hsl(306f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_microsoft_yammer,
        ),
        Entry(
            id = "midi",
            keys = listOf("midi"),
            color = Color.hsl(341f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_midi,
        ),
        Entry(
            id = "mixx",
            keys = listOf("mixx"),
            color = Color.hsl(276f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_mixx,
        ),
        Entry(
            id = "mobile-me",
            keys = listOf("mobile me", "mobile-me"),
            color = Color.hsl(347f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_mobile_me,
        ),
        Entry(
            id = "mr-wong",
            keys = listOf("mr wong", "mr-wong"),
            color = Color.hsl(357f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_mr_wong,
        ),
        Entry(
            id = "msn-messenger",
            keys = listOf("msn messenger", "msn-messenger"),
            color = Color.hsl(126f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_msn_messenger,
        ),
        Entry(
            id = "mubi",
            keys = listOf("mubi"),
            color = Color.hsl(223f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_mubi,
        ),
        Entry(
            id = "mx-linux",
            keys = listOf("mx linux", "mx-linux"),
            color = Color.hsl(228f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_mx_linux,
        ),
        Entry(
            id = "my-space",
            keys = listOf("my space", "my-space"),
            color = Color.hsl(93f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_my_space,
        ),
        Entry(
            id = "nest-wifi",
            keys = listOf("nest wifi", "nest-wifi"),
            color = Color.hsl(218f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_nest_wifi,
        ),
        Entry(
            id = "netflix",
            keys = listOf("netflix"),
            color = Color(0xFFE50914),
            drawableRes = R.drawable.ic_brand_netflix,
        ),
        Entry(
            id = "newsvine",
            keys = listOf("newsvine"),
            color = Color.hsl(337f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_newsvine,
        ),
        Entry(
            id = "nexopia",
            keys = listOf("nexopia"),
            color = Color.hsl(152f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_nexopia,
        ),
        Entry(
            id = "niconico",
            keys = listOf("niconico"),
            color = Color.hsl(310f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_niconico,
        ),
        Entry(
            id = "nintendo-network",
            keys = listOf("nintendo network", "nintendo-network"),
            color = Color.hsl(20f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_nintendo_network,
        ),
        Entry(
            id = "nintendo-switch",
            keys = listOf("nintendo switch", "nintendo-switch"),
            color = Color.hsl(230f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_nintendo_switch,
        ),
        Entry(
            id = "nomad-list",
            keys = listOf("nomad list", "nomad-list"),
            color = Color.hsl(332f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_nomad_list,
        ),
        Entry(
            id = "nuke",
            keys = listOf("nuke"),
            color = Color.hsl(335f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_nuke,
        ),
        Entry(
            id = "obs-studio",
            keys = listOf("obs studio", "obs-studio"),
            color = Color.hsl(231f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_obs_studio,
        ),
        Entry(
            id = "oculus",
            keys = listOf("oculus"),
            color = Color.hsl(81f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_oculus,
        ),
        Entry(
            id = "odnoklassniki",
            keys = listOf("odnoklassniki"),
            color = Color.hsl(233f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_odnoklassniki,
        ),
        Entry(
            id = "open-access",
            keys = listOf("open access", "open-access"),
            color = Color.hsl(265f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_open_access,
        ),
        Entry(
            id = "openai",
            keys = listOf("openai"),
            color = Color.hsl(40f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_openai,
        ),
        Entry(
            id = "open-container-initiative",
            keys = listOf("open container initiative", "open-container-initiative"),
            color = Color.hsl(223f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_open_container_initiative,
        ),
        Entry(
            id = "openvpn",
            keys = listOf("openvpn"),
            color = Color.hsl(318f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_openvpn,
        ),
        Entry(
            id = "oracle",
            keys = listOf("oracle"),
            color = Color.hsl(132f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_oracle,
        ),
        Entry(
            id = "origin",
            keys = listOf("origin"),
            color = Color.hsl(248f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_origin,
        ),
        Entry(
            id = "orkut",
            keys = listOf("orkut"),
            color = Color.hsl(201f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_orkut,
        ),
        Entry(
            id = "osmc",
            keys = listOf("osmc"),
            color = Color.hsl(288f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_osmc,
        ),
        Entry(
            id = "overcast",
            keys = listOf("overcast"),
            color = Color.hsl(67f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_overcast,
        ),
        Entry(
            id = "path",
            keys = listOf("path"),
            color = Color.hsl(107f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_path,
        ),
        Entry(
            id = "patreon",
            keys = listOf("patreon"),
            color = Color.hsl(39f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_patreon,
        ),
        Entry(
            id = "paypal",
            keys = listOf("paypal", "pay pal"),
            color = Color(0xFF003087),
            drawableRes = R.drawable.ic_brand_paypal,
        ),
        Entry(
            id = "photobucket",
            keys = listOf("photobucket"),
            color = Color.hsl(272f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_photobucket,
        ),
        Entry(
            id = "picasa",
            keys = listOf("picasa"),
            color = Color.hsl(295f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_picasa,
        ),
        Entry(
            id = "pingchat",
            keys = listOf("pingchat"),
            color = Color.hsl(324f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_pingchat,
        ),
        Entry(
            id = "pinterest",
            keys = listOf("pinterest"),
            color = Color.hsl(28f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_pinterest,
        ),
        Entry(
            id = "pixabay",
            keys = listOf("pixabay"),
            color = Color.hsl(266f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_pixabay,
        ),
        Entry(
            id = "playerfm",
            keys = listOf("playerfm"),
            color = Color.hsl(70f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_playerfm,
        ),
        Entry(
            id = "player-me",
            keys = listOf("player me", "player-me"),
            color = Color.hsl(260f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_player_me,
        ),
        Entry(
            id = "playstation",
            keys = listOf("playstation"),
            color = Color.hsl(140f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_playstation,
        ),
        Entry(
            id = "plurk",
            keys = listOf("plurk"),
            color = Color.hsl(202f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_plurk,
        ),
        Entry(
            id = "pocket-casts",
            keys = listOf("pocket casts", "pocket-casts"),
            color = Color.hsl(297f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_pocket_casts,
        ),
        Entry(
            id = "proto-io",
            keys = listOf("proto io", "proto-io"),
            color = Color.hsl(9f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_proto_io,
        ),
        Entry(
            id = "protonmail",
            keys = listOf("protonmail"),
            color = Color.hsl(135f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_protonmail,
        ),
        Entry(
            id = "proxmox",
            keys = listOf("proxmox"),
            color = Color.hsl(351f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_proxmox,
        ),
        Entry(
            id = "qik",
            keys = listOf("qik"),
            color = Color.hsl(163f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_qik,
        ),
        Entry(
            id = "qq",
            keys = listOf("qq"),
            color = Color.hsl(256f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_qq,
        ),
        Entry(
            id = "qualcomm",
            keys = listOf("qualcomm"),
            color = Color.hsl(87f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_qualcomm,
        ),
        Entry(
            id = "rdio",
            keys = listOf("rdio"),
            color = Color.hsl(76f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_rdio,
        ),
        Entry(
            id = "reason-studios",
            keys = listOf("reason studios", "reason-studios"),
            color = Color.hsl(208f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_reason_studios,
        ),
        Entry(
            id = "reddit",
            keys = listOf("reddit"),
            color = Color(0xFFFF4500),
            drawableRes = R.drawable.ic_brand_reddit,
        ),
        Entry(
            id = "renren",
            keys = listOf("renren"),
            color = Color.hsl(144f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_renren,
        ),
        Entry(
            id = "retweet",
            keys = listOf("retweet"),
            color = Color.hsl(108f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_retweet,
        ),
        Entry(
            id = "riot-games",
            keys = listOf("riot games", "riot-games"),
            color = Color.hsl(334f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_riot_games,
        ),
        Entry(
            id = "rss-feed",
            keys = listOf("rss feed", "rss-feed"),
            color = Color.hsl(249f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_rss_feed,
        ),
        Entry(
            id = "shadow-tech",
            keys = listOf("shadow tech", "shadow-tech"),
            color = Color.hsl(117f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_shadow_tech,
        ),
        Entry(
            id = "shazam",
            keys = listOf("shazam"),
            color = Color.hsl(272f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_shazam,
        ),
        Entry(
            id = "sina-weibo",
            keys = listOf("sina weibo", "sina-weibo"),
            color = Color.hsl(46f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_sina_weibo,
        ),
        Entry(
            id = "sketch",
            keys = listOf("sketch"),
            color = Color.hsl(322f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_sketch,
        ),
        Entry(
            id = "skype",
            keys = listOf("skype"),
            color = Color.hsl(80f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_skype,
        ),
        Entry(
            id = "slack",
            keys = listOf("slack"),
            color = Color(0xFF4A154B),
            drawableRes = R.drawable.ic_brand_slack,
        ),
        Entry(
            id = "slash-dot",
            keys = listOf("slash dot", "slash-dot"),
            color = Color.hsl(201f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_slash_dot,
        ),
        Entry(
            id = "slide-share",
            keys = listOf("slide share", "slide-share"),
            color = Color.hsl(353f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_slide_share,
        ),
        Entry(
            id = "smug-mug",
            keys = listOf("smug mug", "smug-mug"),
            color = Color.hsl(20f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_smug_mug,
        ),
        Entry(
            id = "snapchat",
            keys = listOf("snapchat"),
            color = Color.hsl(328f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_snapchat,
        ),
        Entry(
            id = "snapdragon",
            keys = listOf("snapdragon"),
            color = Color.hsl(19f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_snapdragon,
        ),
        Entry(
            id = "soundcloud",
            keys = listOf("soundcloud"),
            color = Color.hsl(10f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_soundcloud,
        ),
        Entry(
            id = "spark",
            keys = listOf("spark"),
            color = Color.hsl(25f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_spark,
        ),
        Entry(
            id = "spinrilla",
            keys = listOf("spinrilla"),
            color = Color.hsl(146f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_spinrilla,
        ),
        Entry(
            id = "spotify",
            keys = listOf("spotify"),
            color = Color(0xFF1DB954),
            drawableRes = R.drawable.ic_brand_spotify,
        ),
        Entry(
            id = "square-enix",
            keys = listOf("square enix", "square-enix"),
            color = Color.hsl(246f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_square_enix,
        ),
        Entry(
            id = "squidoo",
            keys = listOf("squidoo"),
            color = Color.hsl(66f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_squidoo,
        ),
        Entry(
            id = "stackoverflow",
            keys = listOf("stackoverflow"),
            color = Color.hsl(216f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_stackoverflow,
        ),
        Entry(
            id = "steam",
            keys = listOf("steam"),
            color = Color(0xFF171A21),
            drawableRes = R.drawable.ic_brand_steam,
        ),
        Entry(
            id = "steinberg",
            keys = listOf("steinberg"),
            color = Color.hsl(313f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_steinberg,
        ),
        Entry(
            id = "stellar",
            keys = listOf("stellar"),
            color = Color.hsl(297f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_stellar,
        ),
        Entry(
            id = "stitcher",
            keys = listOf("stitcher"),
            color = Color.hsl(124f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_stitcher,
        ),
        Entry(
            id = "streaming",
            keys = listOf("streaming"),
            color = Color.hsl(18f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_streaming,
        ),
        Entry(
            id = "streamplay",
            keys = listOf("streamplay"),
            color = Color.hsl(328f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_streamplay,
        ),
        Entry(
            id = "stripe",
            keys = listOf("stripe"),
            color = Color.hsl(341f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_stripe,
        ),
        Entry(
            id = "studen-circle-network",
            keys = listOf("studen circle network", "studen-circle-network"),
            color = Color.hsl(215f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_studen_circle_network,
        ),
        Entry(
            id = "stumble-upon-2ing",
            keys = listOf("stumble upon 2ing", "stumble-upon-2ing"),
            color = Color.hsl(16f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_stumble_upon_2ing,
        ),
        Entry(
            id = "stumble-upong-1ing",
            keys = listOf("stumble upong 1ing", "stumble-upong-1ing"),
            color = Color.hsl(238f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_stumble_upong_1ing,
        ),
        Entry(
            id = "ted",
            keys = listOf("ted"),
            color = Color.hsl(75f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_ted,
        ),
        Entry(
            id = "telegram",
            keys = listOf("telegram"),
            color = Color(0xFF26A5E4),
            drawableRes = R.drawable.ic_brand_telegram,
        ),
        Entry(
            id = "tencent-weiboing",
            keys = listOf("tencent weiboing", "tencent-weiboing"),
            color = Color.hsl(230f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_tencent_weiboing,
        ),
        Entry(
            id = "thread-logo",
            keys = listOf("thread logo", "thread-logo"),
            color = Color.hsl(214f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_thread_logo,
        ),
        Entry(
            id = "tidal",
            keys = listOf("tidal"),
            color = Color.hsl(218f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_tidal,
        ),
        Entry(
            id = "tiktok",
            keys = listOf("tiktok"),
            color = Color(0xFF010101),
            drawableRes = R.drawable.ic_brand_tiktok,
        ),
        Entry(
            id = "tinder",
            keys = listOf("tinder"),
            color = Color.hsl(156f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_tinder,
        ),
        Entry(
            id = "trello",
            keys = listOf("trello"),
            color = Color.hsl(108f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_trello,
        ),
        Entry(
            id = "tuenti",
            keys = listOf("tuenti"),
            color = Color.hsl(309f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_tuenti,
        ),
        Entry(
            id = "tumblr",
            keys = listOf("tumblr"),
            color = Color.hsl(296f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_tumblr,
        ),
        Entry(
            id = "tunein",
            keys = listOf("tunein"),
            color = Color.hsl(267f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_tunein,
        ),
        Entry(
            id = "twitch",
            keys = listOf("twitch"),
            color = Color(0xFF9146FF),
            drawableRes = R.drawable.ic_brand_twitch,
        ),
        Entry(
            id = "twitter",
            keys = listOf("twitter"),
            color = Color(0xFF1D9BF0),
            drawableRes = R.drawable.ic_brand_twitter,
        ),
        Entry(
            id = "ubisoft",
            keys = listOf("ubisoft"),
            color = Color.hsl(124f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_ubisoft,
        ),
        Entry(
            id = "unreal-engine",
            keys = listOf("unreal engine", "unreal-engine"),
            color = Color.hsl(354f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_unreal_engine,
        ),
        Entry(
            id = "unspash",
            keys = listOf("unspash"),
            color = Color.hsl(130f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_unspash,
        ),
        Entry(
            id = "uplabs",
            keys = listOf("uplabs"),
            color = Color.hsl(95f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_uplabs,
        ),
        Entry(
            id = "viddler",
            keys = listOf("viddler"),
            color = Color.hsl(178f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_viddler,
        ),
        Entry(
            id = "vimeo",
            keys = listOf("vimeo"),
            color = Color.hsl(290f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_vimeo,
        ),
        Entry(
            id = "virustotal",
            keys = listOf("virustotal"),
            color = Color.hsl(61f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_virustotal,
        ),
        Entry(
            id = "visa",
            keys = listOf("visa"),
            color = Color.hsl(105f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_visa,
        ),
        Entry(
            id = "v-kontakte",
            keys = listOf("v kontakte", "v-kontakte", "vk", "vkontakte"),
            color = Color.hsl(68f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_v_kontakte,
        ),
        Entry(
            id = "vlc",
            keys = listOf("vlc"),
            color = Color.hsl(107f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_vlc,
        ),
        Entry(
            id = "vodafone",
            keys = listOf("vodafone"),
            color = Color.hsl(180f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_vodafone,
        ),
        Entry(
            id = "vortex",
            keys = listOf("vortex"),
            color = Color.hsl(210f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_vortex,
        ),
        Entry(
            id = "vray",
            keys = listOf("vray"),
            color = Color.hsl(328f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_vray,
        ),
        Entry(
            id = "w3",
            keys = listOf("w3"),
            color = Color.hsl(48f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_w3,
        ),
        Entry(
            id = "wear-os",
            keys = listOf("wear os", "wear-os"),
            color = Color.hsl(298f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_wear_os,
        ),
        Entry(
            id = "wechat",
            keys = listOf("wechat"),
            color = Color(0xFF07C160),
            drawableRes = R.drawable.ic_brand_wechat,
        ),
        Entry(
            id = "wechat-pay",
            keys = listOf("wechat pay", "wechat-pay"),
            color = Color.hsl(171f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_wechat_pay,
        ),
        Entry(
            id = "wetv",
            keys = listOf("wetv"),
            color = Color.hsl(156f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_wetv,
        ),
        Entry(
            id = "whatsapp",
            keys = listOf("whatsapp", "whats app"),
            color = Color(0xFF25D366),
            drawableRes = R.drawable.ic_brand_whatsapp,
        ),
        Entry(
            id = "whitesource",
            keys = listOf("whitesource"),
            color = Color.hsl(178f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_whitesource,
        ),
        Entry(
            id = "wip",
            keys = listOf("wip"),
            color = Color.hsl(198f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_wip,
        ),
        Entry(
            id = "wise",
            keys = listOf("wise"),
            color = Color.hsl(210f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_wise,
        ),
        Entry(
            id = "woocommerce",
            keys = listOf("woocommerce"),
            color = Color.hsl(314f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_woocommerce,
        ),
        Entry(
            id = "wordpress",
            keys = listOf("wordpress", "wp.com"),
            color = Color.hsl(129f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_wordpress,
        ),
        Entry(
            id = "xbox-live",
            keys = listOf("xbox live", "xbox-live"),
            color = Color.hsl(100f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_xbox_live,
        ),
        Entry(
            id = "xing",
            keys = listOf("xing"),
            color = Color.hsl(166f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_xing,
        ),
        Entry(
            id = "xsplit",
            keys = listOf("xsplit"),
            color = Color.hsl(258f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_xsplit,
        ),
        Entry(
            id = "x-twitter",
            keys = listOf("x twitter", "x-twitter", "twitter", "x.com"),
            color = Color(0xFF1D9BF0),
            drawableRes = R.drawable.ic_brand_x_twitter,
        ),
        Entry(
            id = "yahoo",
            keys = listOf("yahoo"),
            color = Color.hsl(282f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_yahoo,
        ),
        Entry(
            id = "yelp",
            keys = listOf("yelp"),
            color = Color.hsl(88f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_yelp,
        ),
        Entry(
            id = "youtube",
            keys = listOf("youtube", "youtu.be"),
            color = Color(0xFFFF0000),
            drawableRes = R.drawable.ic_brand_youtube,
        ),
        Entry(
            id = "youtube-clip",
            keys = listOf("youtube clip", "youtube-clip"),
            color = Color.hsl(36f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_youtube_clip,
        ),
        Entry(
            id = "youtube-gaming",
            keys = listOf("youtube gaming", "youtube-gaming"),
            color = Color.hsl(13f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_youtube_gaming,
        ),
        Entry(
            id = "youtube-music",
            keys = listOf("youtube music", "youtube-music"),
            color = Color.hsl(267f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_youtube_music,
        ),
        Entry(
            id = "youtube-studio",
            keys = listOf("youtube studio", "youtube-studio"),
            color = Color.hsl(212f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_youtube_studio,
        ),
        Entry(
            id = "youtube-tv",
            keys = listOf("youtube tv", "youtube-tv"),
            color = Color.hsl(256f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_youtube_tv,
        ),
        Entry(
            id = "zcool",
            keys = listOf("zcool"),
            color = Color.hsl(239f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_zcool,
        ),
        Entry(
            id = "zoom",
            keys = listOf("zoom"),
            color = Color(0xFF2D8CFF),
            drawableRes = R.drawable.ic_brand_zoom,
        ),
        Entry(
            id = "zootool",
            keys = listOf("zootool"),
            color = Color.hsl(232f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_zootool,
        ),
        Entry(
            id = "z-wave",
            keys = listOf("z wave", "z-wave"),
            color = Color.hsl(234f, 0.50f, 0.42f),
            drawableRes = R.drawable.ic_brand_z_wave,
        ),
    )

    private val byIdMap: Map<String, Entry> by lazy {
        entries.associateBy { it.id }
    }

    fun byId(id: String): Entry? = byIdMap[id]
}